# Program1

In [1]:
import numpy as np

arr = np.around(3.1666, 2)
arr2=np.floor(7.99999)
arr3=np.ceil(-4.66)
arr4= np.fix([-3.1666, 3.6667])
arr5 = np.trunc([-3.1666, 3.6667])

print(arr)
print(arr2)
print(arr3)
print(arr4)
print(arr5)

3.17
7.0
-4.0
[-3.  3.]
[-3.  3.]


# Program 2

In [9]:
import numpy as np

array = np.array([1, 2, 3, 4, 5])
print("NumPy Array:", array)

mean_value = np.mean(array)
sum_value = np.sum(array)
print("Mean:", mean_value)
print("Sum:", sum_value)

reshaped_array = array.reshape((5, 1))
print("Reshaped Array:\n", reshaped_array)

matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])
matrix_product = np.dot(matrix_a, matrix_b)
print("Matrix Product:\n", matrix_product)

reshaped_array = array.reshape((5, 1))
print("Reshaped Array:\n", reshaped_array)

random_numbers = np.random.rand(3, 3)
print("Random Numbers:\n", random_numbers)

rounded_numbers = np.around(random_numbers)
print("Rounded Numbers:\n", rounded_numbers)

floored_numbers = np.floor(random_numbers)
print("Floored Numbers:\n", floored_numbers)

sliced_array = array[1:4]
print("Sliced Array:", sliced_array)


NumPy Array: [1 2 3 4 5]
Mean: 3.0
Sum: 15
Reshaped Array:
 [[1]
 [2]
 [3]
 [4]
 [5]]
Matrix Product:
 [[19 22]
 [43 50]]
Reshaped Array:
 [[1]
 [2]
 [3]
 [4]
 [5]]
Random Numbers:
 [[0.81669302 0.85905608 0.7978291 ]
 [0.58307262 0.41696988 0.60609696]
 [0.09821912 0.14567623 0.57577227]]
Rounded Numbers:
 [[1. 1. 1.]
 [1. 0. 1.]
 [0. 0. 1.]]
Floored Numbers:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Sliced Array: [2 3 4]


# Program 3

In [7]:
import numpy as np

a = np.array([1, 2, 3, 6, 9, 11, 34, 56])    

reshaped_array = a.reshape((2, 4))
print("Reshaped Array:\n", reshaped_array)

print(reshaped_array[0:2, 1:2])  

b = np.array([[1, 2], [3, 4]])       
c = np.zeros((2, 3))                  
d = np.ones((3, 2))                   
f = np.arange(0, 10, 2)               
g = np.linspace(0, 1, 6)             

print(a, b, c, d, f, g)


Reshaped Array:
 [[ 1  2  3  6]
 [ 9 11 34 56]]
[[ 2]
 [11]]
[ 1  2  3  6  9 11 34 56] [[1 2]
 [3 4]] [[0. 0. 0.]
 [0. 0. 0.]] [[1. 1.]
 [1. 1.]
 [1. 1.]] [0 2 4 6 8] [0.  0.2 0.4 0.6 0.8 1. ]


# Program 4

In [8]:
import numpy as np

x = np.array([[1,2,3],[4,5,6]])
y = np.array([[7,8,9],[10,11,12]])
print(x + y)
print(x * 2)
print(x + np.array([1,2,3]))      

[[ 8 10 12]
 [14 16 18]]
[[ 2  4  6]
 [ 8 10 12]]
[[2 4 6]
 [5 7 9]]


# Program 5

In [9]:
import numpy as np

rand_arr = np.random.rand(2, 2)
rand_int = np.random.randint(5, 10, size=(2,3))
rand_norm = np.random.normal(0, 1, size=(3,3))
print(rand_arr, rand_int, rand_norm)


[[0.80944126 0.27647195]
 [0.45500659 0.92164204]] [[6 8 6]
 [6 6 6]] [[ 1.70608477  0.22679931  0.04126574]
 [-0.91179941 -0.72746182  0.31844095]
 [ 1.01052349 -0.53031098  0.48972452]]
